### ISSUE TITLE
PyPI package not working for Python 3

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geoserver-restconfig#1]
**Describe the bug**
PyPI returns an error when trying to install geoserver-restconfig==1.0.1, for Python 3 (pip3) although the version is advertized as available

**To Reproduce**
1. pip3 install geoserver-restconfig==1.0.1

**Screenshots**
![image](https://user-images.githubusercontent.com/571129/62466769-6ccd1a80-b792-11e9-8b98-77a267a6a930.png)

**Desktop (please complete the following information):**
 - Linux Ubuntu 18.04

**Comment by giohappy** [comment]
Indeed the wheels for Py3 seem to be not available: https://pypi.python.org/simple/geoserver-restconfig

**Comment by afabiani** [comment]
Fixed by `pip3 install geoserver-restconfig==1.0.2`
